# Adds namespace to all resources.
namespace: application-service-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: application-service-

resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
- envs:
  - github.properties
  name: github-config
- envs:
  - devfile_registry.properties
  name: devfile-registry-config
  
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: quay.io/jcollier/application-service
  newTag: latest
