# Adds namespace to all resources.
namespace: application-service-system

resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
- envs:
  - github.properties
  name: github-config
- envs:
  - devfile_registry.properties
  name: devfile-registry-config
- envs:
    - feature_flag.properties
  name: feature-flag-config
  
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: quay.io/konflux-ci/application-service
  newTag: next
