apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: application-service.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: HASServiceDetectionQuery is the Schema for the hasservicedetectionqueries
        API
      displayName: HASService Detection Query
      kind: HASServiceDetectionQuery
      name: hasservicedetectionqueries.appstudio.redhat.com
      version: v1alpha1
    - description: HASApplication is the Schema for the hasapplications API
      displayName: HASApplication
      kind: HASApplication
      name: hasapplications.appstudio.redhat.com
      version: v1alpha1
    - description: HASComponentDetectionQuery is the Schema for the hascomponentdetectionqueries
        API
      displayName: HASComponent Detection Query
      kind: HASComponentDetectionQuery
      name: hascomponentdetectionqueries.appstudio.redhat.com
      version: v1alpha1
    - description: HASComponent is the Schema for the hascomponents API
      displayName: HASComponent
      kind: HASComponent
      name: hascomponents.appstudio.redhat.com
      version: v1alpha1
    - description: HASPush is the Schema for the haspushes API
      displayName: HASPush
      kind: HASPush
      name: haspushes.appstudio.redhat.com
      version: v1alpha1
  description: Hybrid Application Service operator
  displayName: Hybrid Application Service
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - has
  - appstudio
  - redhat
  - kubernetes
  - application-service
  links:
  - name: Application Service
    url: https://application-service.domain
  maintainers:
  - email: jcollier@redhat.com
    name: John Collier
  - email: mfaisal@redhat.com
    name: Maysun Faisal
  - email: eyuen@redhat.com
    name: Elson Yuen
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.0
