apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: application-sample
spec:
  # Add fields here
  displayName: "petclinic"
  description: "application definition for petclinic-app"
